In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size=10000


In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[4273, 358, 7226, 3628], [4273, 358, 7226, 6827], [4273, 4440, 7226, 8966], [6522, 6864, 8860, 6366, 5025], [6522, 6864, 8860, 6366, 9122], [9612, 4273, 6142, 7226, 4971], [2794, 2273, 4486, 6366]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np


In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4273  358 7226 3628]
 [   0    0    0    0 4273  358 7226 6827]
 [   0    0    0    0 4273 4440 7226 8966]
 [   0    0    0 6522 6864 8860 6366 5025]
 [   0    0    0 6522 6864 8860 6366 9122]
 [   0    0    0 9612 4273 6142 7226 4971]
 [   0    0    0    0 2794 2273 4486 6366]]


In [8]:
dim=10


In [9]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))


1/1 [==============================] - 0s 109ms/step
[[[-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483
   -0.04083246  0.01774712  0.00648415 -0.00337497 -0.04762229]
  [-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483
   -0.04083246  0.01774712  0.00648415 -0.00337497 -0.04762229]
  [-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483
   -0.04083246  0.01774712  0.00648415 -0.00337497 -0.04762229]
  [-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483
   -0.04083246  0.01774712  0.00648415 -0.00337497 -0.04762229]
  [ 0.04216233 -0.02807379 -0.01209809  0.00525919  0.01230775
    0.04021699  0.03270428  0.03653244  0.02405405  0.02038569]
  [ 0.02345947  0.00294471  0.02550104 -0.02734821  0.04079118
    0.00830157  0.00544857  0.01672213 -0.04776524 -0.01986893]
  [-0.02482875  0.01036841  0.01225729 -0.01797125 -0.0168991
   -0.02789416 -0.04820169 -0.04055555  0.02453187 -0.04419335]
  [ 0.0221259   0.00098194 -0.03909093  0.00265003 -0.01353

In [12]:
embedded_docs[0]


array([   0,    0,    0,    0, 4273,  358, 7226, 3628], dtype=int32)

In [13]:
print(model.predict(embedded_docs)[0])


1/1 [==============================] - 0s 20ms/step
[[-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483 -0.04083246
   0.01774712  0.00648415 -0.00337497 -0.04762229]
 [-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483 -0.04083246
   0.01774712  0.00648415 -0.00337497 -0.04762229]
 [-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483 -0.04083246
   0.01774712  0.00648415 -0.00337497 -0.04762229]
 [-0.04879695  0.02569917 -0.02425146  0.04249443 -0.02201483 -0.04083246
   0.01774712  0.00648415 -0.00337497 -0.04762229]
 [ 0.04216233 -0.02807379 -0.01209809  0.00525919  0.01230775  0.04021699
   0.03270428  0.03653244  0.02405405  0.02038569]
 [ 0.02345947  0.00294471  0.02550104 -0.02734821  0.04079118  0.00830157
   0.00544857  0.01672213 -0.04776524 -0.01986893]
 [-0.02482875  0.01036841  0.01225729 -0.01797125 -0.0168991  -0.02789416
  -0.04820169 -0.04055555  0.02453187 -0.04419335]
 [ 0.0221259   0.00098194 -0.03909093  0.00265003 -0.01353759 -0.0176607
